### PR TITLE
Update umi7_1.txt

### PR DESCRIPTION
**Pull request by dreamenddischarger**

### CODE REVIEW

**Comment by ooa113y** [comment]
Hey, thanks a lot for the contribution! Any reason you closed this (and all the other PRs)? I'm more than happy to accept the help, but if you feel there's something else to do here then please let me know when it's ready to merge. Thanks again!

**Comment by ooa113y** [comment]
Thanks so much for your attention!
Regarding the witch names, please consult the original translation files. What I've been doing so far is put the names they have in caps in the original into small caps (e.g. EVA -> Eᴠᴀ, MARIA -> Mᴀʀɪᴀ, etc). However, Witch-Hunt does not apply this logic the same way that Umineko Project does, and I want to maintain that for the port. In other words, Beatrice is written normally, since it's not capitalised in the original translation. Likewise for, say, Virgilia. In general, WH seems to have followed the principle of only capitalising the names when they are used by both Humans and Witches, whereas Umineko Project turned all of them into small caps.

**Comment by dreamenddischarger** [comment]
I also just remembered something, the Witch Hunt script has translated images and IIRC they don't match with Umineko Project's (as well as being less stylish lol), should we bother adding those or leaving them as is and people can replace it themselves?

**Comment by ooa113y** [comment]
Replacing images is problematic because Umineko Project will complain about changed files. I know they have a system for language packs to add their own files, but I could never figure out how it works... So unless you have any idea how to do that, images will have to stay as is

**Comment by dreamenddischarger** [comment]
Another question... sorry I keep opening this specific issue, I hope it's okay to treat it as a message hub since GitHub doesn't have a DM system as far as I know lol (or we could exchange some other social media I guess), anyways, some lines have {n} at the beginning, I'm supposed to keep those too, right? That's what I've been doing, but just making sure. I'm looking into the images thing by the way, I hope we can figure something out

**Comment by ooa113y** [comment]
The `{n}` doesn't matter a whole lot, so I'd say don't bother with it? It effectively is a newline character, so if the engine encounters it it starts another line of text. UmiPro puts them all over the place, but the WH translation barely ever uses them at all (they don't show up in the original script due to how I handled the extraction, but it's fairly obvious *where* you should put them, mostly in the long NVL sections).

**Comment by ooa113y** [comment]
Regarding exchanging social media information, sure, I wouldn't mind. You could add me on Discord with the tag `O[A]#0542`. I shall remove this comment once you add me so that I don't get too much spam, so that's why I'm posting this separately.

**Comment by ooa113y** [comment]
Speaking of, I already merged all the files for chapters 0-9 and fixed up the remaining issues. You can move on to working on the next chapters now (assuming you still have time, of course!)

**Pull request closed without merging**
